label splashscreen:
    return

define persistent.dialogueBoxOpacity = 1.0

label start:
    define mh = Character('Miss Hill' , color="#11D7EE")
    define d = Character('[name]' , color="#85D7EE")
    define n = Character('Nami' , color="#A80808")
    define m = Character('Nojiko', color="#585858")
    define may = Character('Maja', color="#E8D41F")
    define maj = Character('Maja', color="#E8D41F")
    define u = Character('Unknown Person' , color="#482E78")
    define s = Character('Summer' , color="#19CE1F")
    define na = Character('Nadia' , color="#F46931")
    define ay = Character('Ayua' , color="#01FF71")
    define v = Character('Victoria' , color="#ffcc66")
    define dr = Character('Doctor' , color="#ecd9c6")
    define j = Character('Jeffrey' , color="#B3A7AE")
    define mi = Character('Mila' , color="#F4319B")
    define po = Character('Police Officer' , color="#4BA5D2")
    define b = Character('Bella' , color="#F7B70E")
    define t = Character('Trey' , color="#9EC8F2")
    define ma = Character('Miss Marla' , color="#6D1046")
    define ms = Character('Mister Stahl' , color="#68D7EE")
    define so = Character('Sonya' , color="#187FE6")
    define bari = Character('Barista' , color="#261293")
    define sil = Character('Silvie' , color="#261293")
    define ev = Character('Eva' , color="#11D7EE")
    define bm1 = Character('Amber' , color="#DCBE6D")
    define bm = Character('Amber' , color="#DCBE6D")
    define am = Character('Amber' , color="#DCBE6D")
    define mar = Character('Mario' , color="#4BA5D2")
    define nur = Character('Nurse' , color="#13D74E")
    define cl = Character('Claire' , color="#13D74E")
    define har = Character('Miss Harrison' , color="#13D74E")
    define emi = Character('Emilio' , color="#F46931")
    define sec = Character('Security' , color="#F46931")
    define ci = Character('Cindy' , color="#465951")
    define bari = Character('Barista' , color="#261293")
    define sil = Character('Silvie' , color="#261293")
    define cel = Character('Celina' , color="#f56f42")
    define ka = Character('Karen' , color="#abf5dc")
    define za = Character('Zara' , color="#007bff")
    define sai = Character('Sai' , color="#5e0b12")
    define nan = Character('Nancy' , color="#023f52")
    define nia = Character('Nia' , color="#f25a97")
    define rob = Character('Robin' , color="#fff79c")
    define lay = Character('Layla' , color="#465951")
    define desi = Character('Desiree' , color="#5d3bf5")
    define ow = Character('Shop Owner' , color="#c8c3db")
    define sas = Character('Sasha' , color="#c8c3db")
    define dam = Character('Damian' , color="#e3af84")
    define mh = Character('Coach Hill' , color="#731515")
    define dav = Character('Dave' , color="#731515")
    define lari = Character('Larissa' , color="#731515")
    define moll = Character('Molly' , color="#abf5dc")

    define mw = Character('Jenna' , color="#731515")
    define jen = Character('Jenna' , color="#731515")
    define sg = Character('Susan Gale' , color="#e3af84")
    define dam = Character('Damian' , color="#e3af84")
    define kel = Character('Kelly' , color="#261293")
    define rm = Character('Charlie' , color="#c8c3db")
    define adri = Character('Adrianna' , color="#c8c3db")
    define mad = Character('Madison' , color="#F46931")
    define emilia = Character('Emilia' , color="#F46931")
    define katie = Character('Katie' , color="#007bff")
    define mika = Character('Mikala' , color="#465951")
    define anna = Character('Anna' , color="#ecd9c6")
    define aliy = Character('Alyson' , color="#F7B70E")
    define pen = Character('Penelope' , color="#13D74E")
    define dg = Character('David Goggy' , color="#5d3bf5")
    define pat = Character('Patrick' , color="#261293")
    define lou = Character('Louise' , color="#e3af84")

    $ messages = []
    $ message_time = True
    $ in_history = True
    $ choice_number = True
    $ click_to_continue = False
    $ time_to_send_pm = 2.0
    $ time_to_send_am = 2.0
    $ under_messenger = True

    $ typewriter = False
    $ typewriter_speed = 4
    $ interlocutor_name = "[name]"
    $ interlocutor_name_color = '#c4c4c4'
    $ interlocutor_online = True
    $ interlocutor_typing = True
    $ interlocutor_extra_time = 0.0
    $ interlocutor_typing_speed = 0.025
    $ groupchat_enable = False
    $ groupchat = GroupChat(name='GChat')
    $ groupchat.add( Interlocutor(ID=1, name='Nami', color='#f3f68f') )
    $ groupchat.add( Interlocutor(ID=2, name='Bella', color='#b73b87') )
    $ groupchat.add( Interlocutor(ID=3, name='Trey', color='#009999') )
    $ groupchat.add( Interlocutor(ID=4, name='Jeff', color='#d6ff60') )
    $ groupchat.add( Interlocutor(ID=5, name='Ayua', color='#f3f68f') )
    $ groupchat.add( Interlocutor(ID=6, name='Victoria', color='#b73b87') )
    $ groupchat.add( Interlocutor(ID=7, name='Mila', color='#009999') )
    $ groupchat.add( Interlocutor(ID=9, name='Nojiko', color='#f3f68f') )
    $ groupchat.add( Interlocutor(ID=10, name='Nadia', color='#b73b87') )
    $ active_groupchat = groupchat
    $ dialogue_Mila = []
    $ dialogue_one = []
    $ dialogue_two = []
    $ dialogue_Trey = []
    $ dialogue_GChat = []
    $ dialogue_Nojiko = []
    $ dialogue_vic = []

    pass

    $ name = renpy.input("What is your name?", default = "Nika", length = 14)
    $ name = name.strip()
    s "Do you think it's alive?"
    d "I have no idea."
    s "Touch it."
    d "No! You touch it."
    s "Why is it white?"
    d "Maybe it's an albino?"
    s "Albino spiders?"
    s "Is that a thing?"
    d "I guess? Isn't there some sort of albino of everything?"
    s "Human albinos?"
    d "That's a thing... Like those African people that are white."
    s "Huh..."
    s "I think it's dead!"
    s "*gasp* AHHH!"
    d "NOT DEAD!"
    s "It's... looking at us!"
    d "You- albino spider!"
    s "I think it was napping! It probably had a long day of work!"
    d "Do you think spiders dream?"
    s "Maybe... Maybe they even have.. wet dreams."
    d "Haha, it was probably having one."
    s "And we disturbed it."
    s "No wonder it looks so angry!"
    d "Oh look, look!"
    s "It's super angry at us!"
    d "Careful or it will bolt!"
    s "*gulp*"
    s "I think we should kill it."
    d "Why?"
    s "It saw our faces! It will tell his albino friends and they will come for us!"
    d "That... sounds plausible."
    s "Or- or we can put it into Nami's room!"
    d "That's a good idea!"
    s "But... it could be poisonous."
    d "Mhh- it could be some exotic thing."
    s "Waaaah!"
    d "It's fast!"
    s "You know what?"
    d "We should find another animal and let them fight?"
    s "Yes! Exactly what I thought!"
    s "Man... you just get me!"
    s "*soft whisper* Now let's find another animal so we can watch them fight."
    "You and Summer search in the nearby bushes for a worthy opponent."
    s "I got something!"
    s "There! An orange one!"
    d "How many spiders are here?"
    s "*worried* Oh God... What if they are already on us?"
    d "*pointing at her shoulder and bellowing* Oh god!"
    s "ARRHGH! Get it off me! GET IT OFF!"
    d "*Laughs*!"
    d "There is nothing on you."
    s "You are a jerk!"
    s "Mhhh..."
    d "And now we should let them fight before they run away."
    "She gives you a smile."
    s "My money is on the white one!"
    d "Mine's on the other, then!"
    s "Ohh- I think it's happening!"
    "You both giggle as you wait for the fight to happen."
    s "Wh-what are they doing?"
    d "Uh- I think they're..."
    s "Are they...?"
    d "Yep, they are doing it."
    s "Eww! No bum bum!"
    d "Let's, uh, give them some privacy."
    s "Ewww.. That's so gross.."
    s "Let's go to the cabin! Far away from- them!"
    d "Yes, we should hurry."
    s "You were right.."
    d "I told ya."
    s "It does look a lot creepier with lights on."
    d "It's already dark... We will never find our way home."
    s "I think, uhm, we should sleep here?"
    d "It's our only choice."
    s "We should have gone back!"
    d "Yeah."
    s "Man! It's all your fault! Yours and the albino spider!"
    d "It's your fault! I told you that we should come back another time!"
    s "Yes! But tomorrow I'll be gone on a family vacation!"
    s "I really wanted to see you before I'm gone for two weeks!"
    d "Let's go inside."
    d "What?"
    s "I am scared..."
    d "I'll protect you."
    s "Even if albino spider and his buddies come for me?"
    d "Of course! I will beat them up and then eat them!"
    s "Ewww. *giggle*"
    d "My hands are cold..."
    s "I told you to wear gloves!"
    d "Nami borrowed them."
    s "Nami is stupid!"
    s "But I am still sad that we don't speak anymore..."
    d "I thought you didn't like her?"
    s "I do like her! But, she... *sigh*"
    d "Nami is sad because you ditched her for me..."
    s "I didn't!"
    s "I just really like to spend time with you... because.. I love you.."
    s "I told her that it's nothing personal! But she is so sensitive."
    d "Enough talk about the redhead."
    s "Why is she even red?"
    d "You asked me that a million times already..."
    s "I can warm your hands with my gloves..."
    "You and Summer stare each other in the eyes as she gently rubs your hands to warm them."
    d "(...You are the love of my life.)"
    s "What is it?"
    "A strange glowing flower."
    "You decide to inspect the strange, light-emitting flower."
    s "It is soo beautiful!"
    "You hesitate for a second."
    d "...You see nothing wrong with a strange glowing flower suddenly appearing??"
    s "No. I see them all the time! They are so cute!"
    s "No! Don't drop it!"
    d "Summer?"
    d "Look at me."
    "A yellow-orange light emits from outside of the cabin."
    "More of the strange flowers appear, but this time in yellow."
    "The outside of the cabin is swarmed by these mysterious flowers in different colors."
    d "...It's a dream, isn't it?"
    d "(...This fucking dream...)"
    "Your hand is shaking."
    d "(Fuck this shit.)"
    d "(Five years and it's still...)"
    d "*sigh*"
    d "(Nojiko must be awake.)"
    d "(I should get up... It would be a waste of time to try to sleep in again.)"
    d "(Nami's photos before she broke her camera... She wanted to cheer me up.)"
    d "(And succeeded.)"
    d "(I can't help but smile a little every time I see them. I love the winter.)"
    d "Hey..."
    m "Oh, hey! Why are you awake?"
    d "You know why..."
    m "Oh... You're still dreaming of it?"
    m "Sit down... I'll make you some tea."
    d "No, I-... Actually, some tea sounds nice."
    d "Do you need to work?"
    m "It's Tuesday."
    d "I thought it was Saturday."
    m "You need to get out more."
    d "We'll see."
    m "You know what..."
    m "Go and get some bread from the bakery."
    m "And get some bread rolls for Nami. I don't want to hear her complaining this early in the morning."
    m "[name]?"
    d "Mh? Wait... You were serious?"
    m "Yes."
    d "*sigh* Fine."
    d "(I love the ambience that the fog in the morning provides. A gentle silence.)"
    d "(If only the world could be this silent all the time.)"
    d "(But I'm surrounded by... noise.)"
    d "(Once again, I've caught myself being a misanthrope...)"
    d "(But not all of us are bad... She wasn't...)"
    d "(But she's gone...)"
    d "Summer's gone."
    u "Where is she?"
    d "I was... just speaking about the summer."
    u "No, you weren't. You were talking about a person. Someone who meant something to you."
    u "You have sad eyes."
    u "Excuse me. I shouldn't get involved in other people's business. It's a bad habit."
    d "(Sharing is caring so they say... But I don't want to burden anyone with it.)"
    u "It's so foggy and wet... I almost slipped leaving the house."
    d "Don't take it the wrong way but I'd rather not talk."
    u "Okay, sorry!"
    u "But you have a nice day and I hope you'll find her."
    d "...You too."
    "A flash of light in your peripheral view- You burst forward and try to grab her-"
    "-But the slightly wet hoody slips through your fingers..."
    u "Oh FUCK! Oh FUCK!"
    "She tries to assess the situation but just keeps stumbling over her words."
    u "W-what should we do?!"
    d "*Calm voice* I'd suggest you call an ambulance."
    d "Are you having a stroke? What are you waiting for?"
    u "Nhhh..."
    d "Don't move."
    d "The ambulance will arrive soon."
    "The girl starts hyperventilating."
    d "Don't move."
    u "M-Maja- W-where is Maja?!"
    u "I- I want Maja!"
    d "(She lost consciousness again.)"
    d "(I shouldn't move her in case her spine is compromised...)"
    d "(A cop? Are you fucking kidding me?!)"
    d "(That stupid bitch.)"
    d "Why did you call the police?! She needs an ambulance you fucking idiot!"
    po "*Blurts* An ambulance is on the way."
    "Gently, you move your hand over her forehead."
    d "...Help is on it's way."
    d "But I- I can't stay... I'm sorry."
    d "(Her ID.)"
    d "(It must have been sent flying by the car.)"
    d "(Her wallet shouldn't be far.)"
    d "(Victoria Frohn.)"
    "For a second, you consider going back to give them the ID..."
    d "(Fuck it... I don't have the energy to deal with this shit...)"
    d "(I need to get out of here...)"
    m "-and remember it Nami!"
    n "I will!"
    d "Move your ass, Cheeto."
    n "Hey! You address my ass with its proper title!"
    n "Shhhh... But I forgive you... I heard you went outside... Was the fresh air traumatic?"
    n "Shhh... I'm here..."
    n "Wait a moment! Where are my bread rolls!?"
    d "I was occupied."
    n "Occupied with what, you wormy!?"
    n "Noji! He forgot my rolls!"
    m "I must have some oven rolls somewhere..."
    n "My day is ruined! RUINED!"
    d "Stop being a baby."
    m "Sorry honey. No oven rolls."
    m "[name]! Why didn't you go to the bakery like I told you to?!"
    d "A girl got hit by a car. I took care of her until... shortly before the ambulance arrived."
    m "Is she okay?"
    d "I don't know... and I... don't really care."
    m "Did you put her in the recovery position? The one I showed you two?"
    d "No. Her spine could've been injured."
    m "Good. You've been paying attention."
    d "Oh by the way... I found her wallet. It must have been sent flying by the car."
    m "And you'll give it back."
    d "No."
    d "Can you do it please? I have no interest in seeing her."
    m "No. You will do it!"
    d "You just have to pretend you found it. 'I was walking down the street when I found this precious wallet.'"
    d "'I then tried to find the owner, and well...'"
    d "'Here I am... Victoria.'"
    m "Is that her name?"
    d "Yes, according to her ID."
    n "Was there money in the wallet?"
    d "Nope, no money."
    d "I might go as far as waterboarding you, but I would not steal from a person who just had an accident."
    n "Wow. Now I look like the jerk here..."
    d "Well... You did rent Spa-"
    n "EH, EH, EH, EH!"
    m "*sigh*."
    m "I'm getting ready, and then I'm off to work. Remember, college starts in three weeks!"
    m "And [name], take Victoria her wallet."
    n "Asshole!"
    n "You swore, you wouldn't tell her I rented Spank Canyon 4!"
    d "No? I said I'd hint at it to make you uncomfortable."
    n "What did she look like?"
    d "Mh?"
    n "Victoria."
    d "Like a girl."
    "Nami stares at you. Visibly annoyed."
    d "She was blonde... brown yellow eyes... I guess other people could call her visual appearance... cute."
    n "Maybe she's going to reward you... For saving her life, you know."
    d "Yeah, I could use some money."
    n "I wasn't talking about money."
    d "I know but I chose to ignore your innuendo."
    n "She must be in the Aqualia Hospital, right?"
    d "...Yeah."
    n "I'll come with you."
    d "*sigh*"
    n "You know Nojiko. She won't let it go until you've returned it."
    d "I know... Let's just see if we can find a relative who can take it off our hands."
    n "Let's do it today! I want to seeeee her!"
    d "Why?"
    n "My gut tells me we should go there today! And... Wait! It's whispering something..."
    n "And it told me I should be there with you!"
    d "Your gut is a weirdo."
    n "And in three weeks we're going to college!"
    d "I totally forgot about that."
    n "How could you forget that? Oh right.... Victoria is all you think about."
    d "Oh shut up, Cheeto."
    d "(I totally forgot about the fucking college...)"
    d "(My parents died when I was three.)"
    d "(I can't even remember their faces. But losing them didn't really affect me.)"
    d "(I guess I was too young to know what happened... but Summer... that's a different story.)"
    show text "4 hours later"
    hide text
    jump NamiRoomch1x0

label NamiRoomch1x0:
    n "Hi."
    d "Hi."
    d "Are we just gonna ignore the fact that you're in my room while I'm sleeping."
    n "I think that's for the best."
    d "Weirdo."
    n "I think 9 out of 10 dentists would confirm that you're the weirdo."
    d "*Sigh*"
    d "Alright Cheeto... One time offer... You go alone to the-"
    n "No!"
    "You sit up."
    d "God I hate you."
    n "God hates you, too."
    menu:
        "Insensitive joke":
            d "Is that why neither you nor I have parents?"
            n "Not cool."
        "Joke":
            $ NTJ +=1
            d "Apparently he hates you too... Otherwise you would have more tiddies."
            n "WOW!"
            n "Y-you-..."
            n "Yeah! Fuck you God! What's that about!?"
        "Nothing":
            pass
    d "Ugh... Let's get it done."
    n "Finally, I'm going to meet the infamous Vic!"
    d "Aqualia Hospital... Bus or subway?"
    n "Bus."
    n "Subway's only good if you want to go south to the beach."
    d "Or you need low quality drugs."
    n "Or a five dollar blowjob."
    d "Alright, let's get this done."
    d "I have a headache."
    n "From what?"
    d "The sun... The outside."
    n "Don't let the fresh air in too deep or you might get used to it."
    d "Yo, I have no card."
    n "He has a student ticket."
    d "I do?"
    n "You do! You idiot! We got it two weeks ago with our other college stuff."
    u "I don't care. Just get in."
    d "Must be orange juice..."
    n "Let's hope it is."
    d "Where's Obama's Kebab?"
    n "It's been closed for like a year."
    d "Huh."
    n "I'm excited!"
    n "What does Victoria look like?"
    d "You saw her ID."
    n "It's an ID. Nobody looks good on an ID."
    d "Summer did."
    n "Yeah... She nailed them."
    n "Back to Vic."
    d "I told you already how she looked..."
    d "She's small... Blonde hair... Yellow/hazlenut eyes."
    d "A cute face."
    n "Awww... I hope she's okay."
    n "Yo Dave!"
    dav "Hey Nami!"
    n "Remember Dave?"
    d "No."
    n "The one that was always on Adderall."
    d "I only know Adderall Annie."
    n "Do you feel weird?"
    d "I was never here before. Why would I?"
    n "You were here before."
    n "The uuuh- violent incident."
    d "Oh."
    d "I didn't know it was... here."
    u "Hold the door!"
    n "Hello."
    n "We're looking for Victoria Frohn."
    u "Are you family?"
    n "*Lies* ...Yes."
    n "*Lies* I'm Nami Frohn and this is [name]."
    u "She's in Room 19."
    n "Thanks!"
    d "What?"
    u "What?"
    d "Where'd you get that candy?"
    u "It's mine! I got it for me and a friend!"
    d "I don't want yours. I just want to know if you bought it here."
    u "I'm not telling you!"
    n "Come. Room 19."
    n "Hello."
    u "Who are you?"
    n "I'm Nami."
    n "And this here..."
    d "I'm here."
    n "Uh- this here's [name]."
    u "Okay, and?"
    n "Why are you so rude?"
    u "Victoria almost gets killed in a car accident after someone threatened to end her life."
    u "You could say I'm a little on edge."
    n "It's not like we had something to do with it!"
    u "What's with you? You look suspicious."
    menu:
        "Where can I buy some candy?":
            u "What?"
            d "I saw a child in the waiting hall with some candy... and now I want some, too."
            d "You didn't see a shop around here, did ya?"
            u "*Confused* N-No..."
        "We're here to finish the job.":
            $ JokeFinishTheJob1x0 = True
            d "We're here to finish the job."
            u "HELP!"
            n "God damnit [name]!"
            n "No! Hey! Relax! He's just talking shit!"
        "Say nothing, just stare.":
            u "NURSE! HELP!"
            n "Relax! He's just screwing with you!"
            n "Change your attitude, please."
    n "We're here to bring Victoria her wallet."
    u "Oh, I didn't know that she lost it."
    u "But thanks, you can give it to me."
    n "No."
    n "He will give it to Victoria personally."
    u "Why?"
    n "Why not? He's the one who treated her after the accident."
    u "Oh, I'm sorry... Thanks for that... It's a very stressful time."
    maj "I'm Maja..."
    n "It's okay... We totally understand."
    maj "Could you explain to me what happened?"
    d "She and I met at a crossroad... We walked together for a while, chatted a little and when we were about to part ways, she went to cross the street... and... a car that was driving too fast hit her."
    d "I tried to grab her last second but... She was too far away."
    n "Is she okay?"
    maj "She's alive... They said she was lucky..."
    "Maja starts crying."
    u "Get him into OR 4!"
    u "His lungs collapsed!"
    "The sound of a door opening pulls you back into the present."
    maj "VIC!"
    v "*Weak* Maja?"
    maj "Yes sweety. I'm here."
    v "I don't know what happened."
    maj "You had an accident."
    v "I- I remember you."
    d "I remember you, too."
    v "G-ood."
    d "You don't look that fucked up."
    n "*Whisper* Dude..."
    d "Are you in any pain?"
    v "No... I feel like I've had a really long workout... and didn't drink anything for the past 4 years."
    n "*Sweet* Hi."
    v "Who are you?"
    n "I'm Nami."
    n "[name]'s roomie."
    v "It's so n-nice that you two came."
    d "Right. We're here-"
    n "- We're here to see how you've been and we're so glad you're mostly alright."
    n "We also found your wallet."
    v "Oh. Thank you."
    u "Hello."
    u "How do you feel, Victoria?"
    v "Groggy."
    u "I believe that."
    u "Are you all family?"
    d "No."
    u "Then I'll have to ask you to leave."
    u "We have to go over some important steps."
    maj "Okay sure."
    n "Goodbye. Get well soon!"
    v "Thanks."
    "Maja brings you and Nami to the door."
    maj "Thanks again..."
    n "I hope everything goes well."
    maj "...Yeah."
    maj "Goodbye."
    n "Bye."
    d "Yo! Cheeto. Slow down."
    d "Dude? What's the matter?"
    n "Don't 'Dude' me!"
    n "GOD! YOU COULD'VE AT LEAST SAID 'Get well soon, Victoria.'"
    n "BUT NO! YOU'RE AN INSOLENT FOOL!"
    d "That's why you're mad?"
    n "YES! THAT'S WHY I'M MAD."
    d "She's just some stranger."
    n "It's about more than that! I'm trying so hard to make you likeable... To reintegrate you into society and you always fuck it up!"
    n "We all were shocked when the whole Summer thing went down but MAN!"
    n "It's been years! GET OVER IT!"
    d "What do you think I've been trying to do all this time?!"
    d "Do you think I enjoy my state of mind?!"
    d "I DREAM OF HER almost every single fucking night."
    d "I hear her voice every night!"
    d "So please, stop being a cunt and worry about your own shit."
    n "YOU ARE MY SHIT! I care about you!"
    n "Idiot!"
    "Nami storms off."
    d "*Sigh*"
    d "Thanks."
    d "Do you know what we're gonna eat today?"
    n "Don't talk to me."
    d "(...I might not show it, but I feel bad for Victoria.)"
    d "(I pity her.)"
    d "(She didn't deserve it...)"
    d "(Funny... Lots of things happen to people who don't deserve it.)"
    d "(I would do anything to get some closure.)"
    d "(To find out what happened to you...)"
    d "What are you thinking about?"
    s "Thingies."
    s "All those places on earth... Ya know... I'd really like to visit them someday."
    s "Eat all the weird food... and- and swim with the dolphins."
    s "You can come with me if you want."
    s "Imagine all the things we could do!"
    d "Let exotic animals fight?"
    s "You know it!"
    d "Why do you always buy weird smiley erasers?"
    s "They're cute. Look!"
    s "*giggles* Now they are kissing."
    d "Could be you and me."
    "You and Summer gently rub your heads together."
    d "Can I have one? I don't have an eraser."
    s "Only if you give it back later!"
    d "I promise!"
    s "Good! I'll bless him first!"
    "Summer gives the eraser a kiss."
    s "And now: take good care of him."
    d "(The toxicity of the question: What could've been?)"
    d "(It's torture.)"
    d "(And me being all alone doesn't help...)"
    d "(I can't believe I'm saying this... but college might be the solution.)"
    d "(I'll be forced to socialize.)"
    "A few hours later."
    d "(I need to get good with the Cheeto... I need her.)"
    d "*Sigh*"
    n "Assface."
    d "I'm afraid."
    n "What?"
    d "College is going to start in three weeks and... I don't know if I can handle it."
    n "Dude! Of course you can!"
    n "I'll be there, too!"
    d "I've become so anti social."
    n "I wouldn't say that... Well, you lost your filter."
    n "But I have seen you speak with people. You can still articulate and speak clearly."
    d "My comfort zone is raging."
    n "Fuck your comfort zone."
    n "We'll handle it."
    "Nami gently drags you back and wraps her legs around you."
    d "Do you know anything about the college?"
    n "Except that we didn't even get the chance to look around for other colleges, no."
    n "But I checked some forums and it's a really good college... Even though most of them were complaining about not getting accepted."
    d "I have to think about classes... I don't even know what I'm gonna major in."
    d "Probably people."
    "Nami lets out a little laugh."
    n "...They have a D1 Basketball team..."
    n "Just saying."
    d "I haven't played in... forever."
    n "Talent doesn't vanish. You still got it."
    n "Did you get your uniform?"
    d "No?"
    d "I don't think there's one."
    n "There is."
    d "If it doesn't get here in time, I'll just get one when we're there."
    n "So I found this weird porn site-"
    d "Dude! Come on! No!"
    d "It's traumatizing enough that I sometimes hear you moan."
    n "Can't be! I'm always extremely quiet!"
    n "Noji should be back soon."
    n "I'm gonna go play some games until then..."
    n "And..."
    n "No matter what... You're not alone."
    n "We're always there for each other."
    d "Yea."
    show text "Three weeks later."
    n "ARGH!"
    d "Fucking retard! What- the fuck..."
    n "COLLEGE! GET UP BITCH!"
    d "FUCK OFF!"
    n "YOU WANT ONE OF THESE?!"
    d "You littl-"
    "Nami sprints away!"
    d "(...Fucking Cheeto.)"
    "A slight burst of anxiety shoots through your body."
    d "What's the matter with you cunt?!"
    m "Hey!"
    m "Don't call her names!"
    $ persistent.unlockedImageNami_CH2_8 = True
    d "This moron-"
    n "PEW! PEW!"
    m "I know [name]..."
    m "Nami woke up a little... excited."
    d "*Sigh*."
    m "Did you get your uniform?"
    d "No."
    n "YOU HAD TO ORDER IT!"
    d "There was no uniform!"
    n "Yes, there was! Other students confirmed it!"
    m "You look pale."
    d "How would you feel if some Cheeto on coke bursts into your room after sleeping for barely an hour."
    m "Yeah."
    m "It's gonna be alright."
    d "I'll go get a shower and... get ready."
    n "Yo!"
    n "You'll need to pay me to get through here!"
    n "Nooooo!"
    n "Yeah, you better run!"
    m "Nami... Did you drink coffee?"
    n "Coffee? Good idea!"
    m "Now it's perfect."
    m "You look beautiful."
    n "Thanks!"
    m "I'm so proud of you two."
    d "College is just another way into the rat race."
    d "With additional steps, and that your parents are proud of you."
    m "It can teach you valuable life skills, and you'll always have something to fall back on."
    d "Cheeto?"
    d "You're okay?"
    n "My belly hurts."
    m "You're just nervous."
    n "Soooo nervous... I need some rolls."
    d "It's time."
    d "We'll take the E12 Bus?"
    m "I'll drive you. I want to witness your first steps into adulthood."
    n "Does this include other 'first times', too?"
    m "Why do you say such things?"
    n "I'm so nervous! I joke to calm myself down!"
    d "I'm good."
    m "Let's go."
    n "Do you have any Kaiser rolls?"
    u "Of course."
    n "I'll take three."
    d "You really have problem, you know?"
    n "I do?"
    d "It's called an addiction."
    d "You can't go a day without these stupid rolls."
    n "They're my fuel!"
    n "And they calm down my nerves."
    n "Besides, there are no classes today."
    n "They're going to welcome us first... But you might be in trouble."
    d "Why?"
    n "You forgot to buy the official uniform!"
    d "There was no uniform!"
    n "Other students confirmed it!"
    n "It looked... different on the pictures."
    m "This is the new part of it. It's being renovated as far as I know."
    d "Say... Where are the uniforms?"
    n "This might be a freshmen thingy!"
    d "I don't see her wearing a uniform."
    n "She's probably not a freshman, duh."
    d "Sure."
    n "Fuck off."
    m "Enough."
    d "Don't cry."
    m "You two grew up so fast."
    m "I am so proud of you both."
    m "Take care of [name]."
    n "That's pretty much all I ever do."
    m "And [name] keep an eye on Nami."
    d "That's pretty much all I ever do."
    n "Bullshit!"
    m "*Whisper* Good luck you two."
    d "Have you noticed the looks people are giving you?"
    n "I'm just reminding them that they all forgot their uniform."
    d "Right... I mean... all these people forgot it."
    n "Y-yeah."
    d "Where do we need to go?"
    n "The auditorium."
    n "Hello! Excuse me!"
    u "Tzz."
    n "Uh- what?"
    u "Hi! You must be Nami."
    n "Yes."
    b "I'm Bella. We talked."
    b "I'm glad you managed to get the uniform."
    n "Say... why aren't you wearing one?"
    u "MOR SUCKS!"
    b "Well..."
    b "You see... It could be misconstrued if I were to wear the uniform of a rival college on my first day."
    n "...What?"
    u "Excuse me?"
    u "Did you get lost?"
    n "...No?"
    u "*Sigh*"
    u "Are you in such a desperate need for attention?"
    n "I- I didn't know!"
    u "Follow me. Now."
    d "(Where the hell is the Cheeto going?)"
    "You let your eyes wander through the hall."
    d "(That blonde bitch did something...)"
    "Your eyes meet."
    b "Ugh... I hope he isn't in our classes. We already got enough ugly guys."
    menu:
        "Ignore her.":
            pass
        "These hands are rated E.":
            $ achievement.grant("E for Equality.")
            $ achievement.sync()
            $ Equality1x0 = True
            d "Are you talking about me?"
            b "Maybe."
            b "What if?"
            d "These hands are rated E."
            d "E for equality."
            "The girl laughs."
            b "At least he's funny."
    d "You."
    u "Yes?"
    d "You look lost... which means you're probably a freshman."
    u "Yeah, I am."
    u "Are you a freshman too?"
    d "Yeah."
    u "I'm Trey. Nice to meet you."
    d "I'm [name]."
    d "Apparently we've gotta go to the auditorium."
    t "I heard the freshmen are meeting outside?"
    d "Whatever."
    d "If you want we can go there together."
    t "Sure!"
    t "I'm so excited."
    d "I'm not."
    t "Yeah, I got that feeling from you... You look very unbothered."
    t "College girls..."
    t "You don't see this level in a high school."
    t "Basketball, huh?"
    d "Yeah..."
    t "Are you gonna apply?"
    d "Not sure... Maybe."
    t "I'll go for it."
    t "I played it in high school... I wasn't the best but a little cardio can't hurt."
    d "I have to choose some classes."
    t "Mila!"
    mi "Hey Trey, how are you?"
    t "I'm good!"
    t "This is [name]."
    mi "Hi! Nice to meet you, I'm Mila."
    d "Hi."
    mi "You give me a weird vibe."
    d "You'll get used to it."
    mi "If you had a trench coat I'd be worried you'd shoot up the school."
    d "I promise... I'll shoot you last."
    mi "...Thanks."
    u "Hey Mila!"
    mi "Hey Ayua."
    mi "Does anyone know where we have to go?"
    d "Auditorium."
    t "Outside."
    mi "I heard we're supposed to meet here."
    t "Maybe Jeff knows?"
    mi "Is he already here?"
    mi "Where's [name]?"
    t "Uuh..."
    d "(This should be the Auditorium.)"
    u "Hey! Are you-"
    d "- A freshman."
    j "Great! I'm Jeff."
    d "[name]."
    j "I heard we're meeting here?"
    d "That's what I heard, too."
    d "Others say outside."
    j "Doesn't really matter."
    d "Yeah, they'll find us eventually."
    n "Fuck this place."
    j "Whoa there..."
    n "Sorry..."
    d "Where did you go?"
    n "This uniform..."
    j "Is from a rival college."
    n "Yup... She fooled me."
    d "That blonde bitch?"
    j "Long ponytail, yellow/green eyes?"
    n "Yes. Do you know her?"
    j "Oh yeah... Bella."
    j "I don't want to put her down but... She's a very difficult person."
    t "She's a weirdo."
    t "Hot, but a fucking weirdo."
    mi "Hi!"
    mi "I'm Mila."
    n "Hello, I'm Nami."
    t "I'm Trey."
    n "Hi!"
    j "Yo... What up?"
    t "What up?"
    j "Did you ride a cycle during the summer?"
    t "...No."
    j "Motherfucker."
    mi "But yeah, stay away from Bella."
    mi "It only brings unnecessary trouble."
    n "Oh, I'll get back at her."
    j "Hmm... Are you interested in sports?"
    d "No."
    n "He is."
    n "He's good at basketball."
    j "Nice. I'm also going for the team."
    j "But... you look a little out of shape."
    j "You should come to the gym with us."
    menu:
        "I'll think about it.":
            $ jeff +=1
            $ Jeffgym1x0 = True
            j "Great!"
        "Not at the moment.":
            $ Jeffgym1x0 = False
            $ jeff -=1
            j "Your choice, buddy."
    u "Ah!"
    u "You're all freshmen?"
    mi "Yes."
    ma "I'm Miss Marla."
    ma "Please follow me."
    ma "Where's the rest?"
    lari "Many freshmen apparently decided not to come... As this is not mandatory."
    d "It's not?"
    n "I didn't know."
    mi "I could've slept longer..."
    ma "Welcome to ZPR College!"
    ma "I'm Miss Marla, and I'm a Professor here."
    ma "Larissa here volunteered to help me with today's introduction."
    lari "A big welcome from me, too."
    lari "We'll start with a tour around the campus."
    lari "This here is the reception... If you need any information about the college and its facilities. You can get them here."
    lari "If you have applied for a dorm room or house, you can get your keys here too."
    d "I'm hungry."
    n "Those are my rolls."
    d "I don't want your stupid rolls."
    n "That's what they all say and then..."
    n "BAM! My rolls are gone!"
    n "*Cough* Please continue."
    ma "As I was saying, Karen, who usually works the reception isn't here right now."
    ma "*Mumbles* For whatever reason..."
    ma "Follow me please."
    ma "This is the cafeteria."
    ma "It's also accessible for non-students but students get 50 percent off."
    d "Do you think I can sneak away and grab one of those sandwiches?"
    d "Oh. Wrong Cheeto."
    n "Dude..."
    lari "We'll move on."
    mi "Still pretty expensive here."
    ma "And now about the history of our college."
    d "Kill me now."
    n "Did you just see that topless girl?"
    d "No."
    n "She had nice tiddies."
    n "Let's sneak away."
    mi "I'm in."
    j "Follow me!"
    t "That woman could really go on and on and on..."
    d "I should've gotten a sandwich..."
    n "You can eat my arm."
    d "Who knows where that arm has been."
    n "Do you all know each other?"
    mi "Jeff, Trey and I went to the same high school."
    j "Yeah, many people here are from our old high school."
    mi "At least the smart ones..."
    mi "Trey, how did you get in again?"
    t "Hey!"
    mi "Where are you two from?"
    n "We went to a high school way in the west."
    d "I get the feeling you brought us here for a reason."
    j "Sharp."
    j "Imagine this place being full of people... all watching you make the winning basket... The last 20 meter on the track... or the furthest jump."
    d "Yeah, it does nothing for me."
    j "Nothing?"
    d "I don't care about fame or being known."
    j "What do you care about?"
    d "I don't know... The Cheeto."
    j "You're a cute couple."
    n "Whoa, whoa, woah! We're roomies!"
    j "Oh!"
    mi "I also thought you were a couple."
    t "So did I."
    n "So Mila... Tell me about yourself!"
    j "That's Bella."
    j "She's uh... well, yeah... Not a good person."
    j "The one with the hat. That's Nadia,"
    j "Nice girl. But she isn't very social most of the time."
    t "She's also undateable."
    d "Undateable?"
    t "Every guy that has ever asked her out failed."
    d "Maybe she's asexual."
    j "She isn't."
    j "Nadia's just a little weird... and competitive."
    t "Competitive?"
    j "Have you ever seen her play?"
    t "Play what?"
    j "Anything. Board games, sports... hell, even the math test."
    d "And the other one?"
    j "Ayua."
    t "Oh Ayua... That's one hell of a girl."
    t "Drives a muscle car."
    t "I'm sure she's somehow involved into the racing slash tuning community."
    mi "Didn't she beat you up before?"
    t "..."
    j "Ayua is cool. But don't say anything bad about her friends, that includes Bella."
    t "Ayua's a very skilled fighter and also trains people in various martial arts."
    d "I can imagine... She has an aura around her."
    t "Maybe she just farted?"
    j "Come on... All males agreed that girls don't do that."
    s "You bibi!"
    d "You're the bibi!"
    "(Bibi is pronounced 'Bee Bee' and refers to something baby-like.)"
    s "SEE! BIBI!"
    d "You always foul me!"
    s "Do you hear that?"
    s "IT SOUNDS LIKE A BIBI!"
    mi "Hey."
    d "Hey."
    mi "Mind if we talk for a second?"
    $ milatalk = True
    d "(Stay strong [name]... Don't let the comfort zone win and be nice...)"
    d "Sure."
    mi "I recognize a broken mind when I see one."
    d "My mind isn't broken."
    mi "You're right. It's shattered."
    mi "You remind me of someone. A girl I used to know from high school. Always trying to look normal, nothing weird about her, except that... certain aura."
    d "What aura?"
    mi "An aura that..."
    mi "Hah..."
    mi "That scares me."
    d "And I have that aura, ya?"
    mi "Yes. She killed herself a few weeks before graduation... And you know what's the worst part of it?"
    d "What?"
    mi "I knew about it. I knew that she was having issues. I saw it in her eyes. I felt her inner conflict."
    mi "But I didn't do anything to prevent it. I didn't trust myself. I thought I would annoy her if I speak to her about it."
    mi "And now, she's dead."
    d "And where are you going with this? Do you think I'm going to kill myself?"
    mi "No, there are different types of... 'dealing with it'."
    mi "And you look like a person who'd prefer to hurt others."
    mi "I might be wrong and you'd prefer to kill yourself, too."
    mi "But please just keep in mind that there are people you can talk to."
    menu:
        "Joke.":
            d "I'll keep it in mind when I shoot up the school."
            mi "*Laughs*."
            mi "No, but for real, keep it in mind."
        "I appreciate your concern... But worry about your own stuff.":
            mi "Yeah, sorry."
        "I will.":
            mi "Good."
    n "Oh! I'll get back at her!"
    j "Don't Nami... It's not worth the trouble."
    t "He's right."
    n "Pff! I'll do it anyways!"
    d "Cheeto? Wanna go home?"
    n "No, not yet."
    d "Alright, you stay a little longer but I'm gonna go."
    n "See you later!"
    d "(...She walks too slow to make distance but too fast to overtake in a comfortable way.)"
    d "(Stupid NPC.)"
    u "We're sick of having to hide our boobs behind fabric!"
    u "Same rights for everyone!"
    d "(Where was this damn cafeteria again...)"
    d "(Thank you.)"
    b "*Mumbles* ...What the fuck?"
    d "(Tasted pretty good... with a hint of justice.)"
    "Suddenly, you spot someone."
    d "I had hoped you'd just walk past."
    maj "Me too."
    d "I saw the conflict."
    maj "...*Sigh*"
    maj "Victoria asked for you."
    d "How did you find me?"
    maj "By accident."
    maj "She asked me a week ago to find you."
    maj "I was just bringing in some papers for her when I saw you."
    d "She's coming here, too?"
    maj "Yeah."
    d "I don't believe in coincidences."
    maj "I prefer to believe it's a coincidence because I don't want you two to be connected."
    d "So? You found me. What now?"
    maj "Would you visit her?"
    d "I really don-"
    maj "Please."
    maj "The situation is hard on her... It might really help... and believe me, I wouldn't be asking you if I didn't have to."
    maj "She's very vulnerable right now... and it's taking a toll on her mental health."
    d "Fine."
    d "As long as you take me home afterwards."
    maj "I will."
    maj "Is Nami here, too?"
    d "M-"
    u "STOP THE Raccoon!"
    maj "Uaaah!"
    u "Don't let him near a water supply! "
    maj "This place didn't change a bit..."
    maj "Oh, they finally allowed the 'FreeTheBoobs' movement."
    maj "I remember when we created it... So many suspensions."
    d "...Let's do it."
    d "And if we get the chance to save the Raccoon... We will."
    maj "No way that animal gets into my car."
    maj "She's in her room."
    d "Because I know where her room is..."
    maj "Down the hall on the right."
    maj "And knock before-"
    d "Hey!"
    v "*Gasps*"
    maj "Fucking rowdy!"
    v "Hi!"
    v "Maja found you!"
    d "Yeah, she did."
    v "I'm glad you came by."
    d "I wonder why though?"
    v "I keep dreaming of you."
    d "Well, dreams are just drea-"
    d "(...I wish dreams were just dreams.)"
    v "Please sit down."
    d "How's it going-... I mean..."
    d "Rolling."
    v "Going: Bad... Rolling: Good."
    d "Do you know what's up with your legs?"
    v "I can't feel them."
    d "Nothing?"
    v "I- I imagine some sort of feeling whenever I see someone touch it."
    v "But I think it's just my imagination."
    d "I'm sorry to hear that."
    v "I'll work with what I have."
    d "(She seems pretty strong... Might just be a facade she's putting up in front of me.)"
    d "You seem pretty okay with it."
    v "What's the point in crying over it? It won't change my situation. It will only make it worse."
    v "I'm going to make the best out of it."
    d "You're a positive person. That's the essence to happiness."
    d "(Maja's description was different... But Maja's also going through a lot right now.)"
    d "Back to my question..."
    v "I want to get to know you."
    d "Why?"
    v "I think you're cute."
    d "...Listen, I-"
    v "I-It's okay- I don't want an answer... I just want to put a thought into your head."
    v "It's going to evolve over time and then you can tell me what you think."
    d "Sounds like a plan."
    d "And apparently we're both going to ZPR."
    v "Yeah. I saw your name on the list."
    d "Will you be there tomorrow?"
    v "Yes. At least until next week when I start physical therapy."
    menu:
        "I wish you the best.":
            v "Thanks!"
        "I see.":
            pass
    d "If you uh- got a phone we could stay in contact."
    v "It got destroyed in the accident."
    v "But as soon as I have a new one, I'll give you my number!"
    d "Alright Victoria."
    v "T-Thanks for coming by."
    d "No problem."
    d "(I feel like a little weight got lifted off my shoulders... Apparently I was subconsciously affected by her fate.)"
    d "(But seeing her this 'happy' helped me a little.)"
    d "I'll see you tomorrow... and take care."
    v "Yes... Bye [name]..."
    v "*Whisper* I'll see you..."
    maj "I was uh- just checking the uh- paint."
    "Your raise a brow."
    maj "What? I don't want you to influence her!"
    d "I don't blame you."
    d "You promised me a ride back."
    maj "Yes."
    $ vici = 1
    $ mila = 1
    jump report2